//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkerFox.Shell.ApplicationServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicationServices.INewOrderProcessingService")]
    public interface INewOrderProcessingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewOrderProcessingService/GetOrders", ReplyAction="http://tempuri.org/INewOrderProcessingService/GetOrdersResponse")]
        ParkerFox.Core.Entities.Ecommerce.Order[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewOrderProcessingService/GetOrders", ReplyAction="http://tempuri.org/INewOrderProcessingService/GetOrdersResponse")]
        System.Threading.Tasks.Task<ParkerFox.Core.Entities.Ecommerce.Order[]> GetOrdersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewOrderProcessingServiceChannel : ParkerFox.Shell.ApplicationServices.INewOrderProcessingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewOrderProcessingServiceClient : System.ServiceModel.ClientBase<ParkerFox.Shell.ApplicationServices.INewOrderProcessingService>, ParkerFox.Shell.ApplicationServices.INewOrderProcessingService {
        
        public NewOrderProcessingServiceClient() {
        }
        
        public NewOrderProcessingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewOrderProcessingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewOrderProcessingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewOrderProcessingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ParkerFox.Core.Entities.Ecommerce.Order[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<ParkerFox.Core.Entities.Ecommerce.Order[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
    }
}
