CREATE TABLE [Event]
(
	EventId UNIQUEIDENTIFIER NOT NULL,
	StreamId NVARCHAR(50) NOT NULL,
	Sequence INT NOT NULL,
	[TimeStamp] DATETIME NOT NULL,
	EventType NVARCHAR(255) NOT NULL,
	Body NTEXT NOT NULL,
	PRIMARY KEY(EventId)	
)

CREATE TABLE Stream(
	StreamId NVARCHAR(50) NOT NULL,
	CurrentSequence BIGINT NOT NULL,
	PRIMARY KEY(StreamId)
)